[versions]
# plugins
shadow = "9.2.2"
indra = "3.2.0"
toxopid = "4.1.2"
spotless = "8.0.0"

# sql libraries
sqlite = "3.50.3.0"
h2 = "2.4.240"
mariadb = "3.5.6"
mysql = "9.4.0"

# utilities
slf4md = "1.1.3"
slf4j = "2.0.17"

[libraries]
# sql libraries
sqlite = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }
mariadb = { module = "org.mariadb.jdbc:mariadb-java-client", version.ref = "mariadb" }
mysql = { module = "com.mysql:mysql-connector-j", version.ref = "mysql" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }

# utilities
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

[plugins]
indra-common = { id = "net.kyori.indra", version.ref = "indra" }
indra-publishing = { id = "net.kyori.indra.publishing", version.ref = "indra" }
indra-git = { id = "net.kyori.indra.git", version.ref = "indra" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
toxopid = { id = "com.xpdustry.toxopid", version.ref = "toxopid" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
